package Business;
import DB.ProductReader;

public class Product implements ProductReader{
	
	private String code; 
	private String description;
	private Double price;
	
	//declare constructors
	
	public Product() { 
		code = "";
		description = "";
		price = 0.0;
	
	}
// generated by eclipse:
//	public Product(String code, String description, Double price) {
//		this.code = code;
//		this.description = description;
//		this.price = price;    OR
	
//Wrote this one in class
	
	public Product(String inCode, String inDescription, Double inPrice) {
		code = inCode;
		description = inDescription;
		price = inPrice;
	
		
}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "Product [code=" + code + ", description=" + description + ", price=" + price + "]";
	}
	
	public static void aStaticMethod() {
	System.out.println("an arbitrary static method");
	}
	@Override
	public Product get(String Code) {
		// TODO Auto-generated method stub
		return null;
	}
	@Override
	public String getAll() {
		// TODO Auto-generated method stub
		return null;
	}
	
	
	
//	public String getCode() {
//		return code;
//	}
//	
//	public void setCode(String "C") {
//	
//	code = c;
	}

	
